title: Test Wiki
description: a test wiki
theme: just-the-docs

url: https://devlogsforever-netizen.github.io/Template-Wiki-Test-Attempt-To-Figure-Out-How-It-Works

aux_links: # remove if you don't want this link to appear on your pages
  Github Page: https://devlogsforever-netizen.github.io/Template-Wiki-Test-Attempt-To-Figure-Out-How-It-Works
